portal/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from .views import *

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('birthday', views.BirthdayListView.as_view(), name='birthday'),
    path('add_birthday', views.BirthdayCreateView.as_view(), name='birthday_add'),
    path('update_birthday/<pk>/', views.BirthdayUpdateView.as_view(), name='update_birthday'),
    path('delete_birthday/<pk>/', views.BirthdayDelete.as_view(), name='delete_birthday'),
    path('send', send, name='send'),
    path('<slug:slug>', article_detail, name='article_detail'),
    path('maintest/', views.MaintestListView.as_view(), name='maintest'),
    path('maintest_add/', views.MaintestCreateView.as_view(), name='maintest_add'),
    path('maintest_update/<pk>/', views.MaintestUpdateView.as_view(), name='maintest_update'),
    path('maintest_delete/<pk>/', views.MaintestDeleteview.as_view(), name='maintest_delete'),
    path('parenttest/', views.ParenttestListView.as_view(), name='parenttest'),
    path('parenttest_add/', views.ParenttestCreateView.as_view(), name='parenttest_add'),
    path('parenttest_update/<pk>/', views.ParenttestUpdateView.as_view(), name='parenttest_update'),
    path('parenttest_delete/<pk>/', views.ParenttestDeleteview.as_view(), name='parenttest_delete'),
]

portal/phonebook/urls.py
from django.urls import path, re_path

from . import views

urlpatterns = [
    path('', views.EmployeesListView.as_view(), name='phonebook'),
    path('employees_add/', views.EmployeesCreateView.as_view(), name='employees_add'),
    path('ajax/load-division/', views.load_division, name='ajax_load_division'),
    path('employees_update/<pk>/', views.EmployeesUpdateView.as_view(), name='employees_update'),
    path('employees_delete/<pk>/', views.EmployeesDelete.as_view(), name="employees_delete"),
    path('departments', views.DepartmentListView.as_view(), name='departments'),
    path('department_add', views.DepartmentCreateView.as_view(), name='department_add'),
    path('department_update/<pk>/', views.DepartmentUpdateView.as_view(), name='department_update'),
    path('department_delete/<pk>/', views.DepartmentDelete.as_view(), name="department_delete"),
    path('divisions', views.DivisionListView.as_view(), name='divisions'),
    path('division_add', views.DivisionCreateView.as_view(), name='division_add'),
    path('division_update/<pk>/', views.DivisionUpdateView.as_view(), name='division_update'),
    path('division_delete/<pk>/', views.DivisionDeleteView.as_view(), name='division_delete'),
    re_path(r'^export/xls/$', views.DownloadPhonebook.as_view(), name='download_phonebook'),
]

portal/portal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from portal import settings

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.urls')),
    path('phonebook/', include('phonebook.urls')),
    path('accounts/', include('accounts.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User, Group


class Birthday(models.Model):
    fio = models.CharField(max_length=255, unique=True, verbose_name='Сотрудник')
    fio_kk = models.CharField(max_length=255, unique=True, verbose_name='Қызметкер')
    position = models.CharField(max_length=255, verbose_name='Должность')
    position_kk = models.CharField(max_length=255, verbose_name='Қызмет атауы')
    date = models.DateField(verbose_name='День рождения')
    photo = models.ImageField(upload_to='birthday_photos', verbose_name='Фото')

    class Meta:
        verbose_name = 'День рождения'
        verbose_name_plural = 'Дни рождения'
        ordering = ['fio']

    def __str__(self):
        return self.fio


class News(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name=_('Новость'))
    slug = models.SlugField(unique=True)
    text = models.TextField(verbose_name=_('Текст'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Автор'))
    division = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name=_('Отдел'))

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'slug': self.slug})


class MainTest(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name=_('Родительский'))

    def __str__(self):
        return self.title


class ParentTest(models.Model):
    title = models.ForeignKey(MainTest, on_delete=models.CASCADE, verbose_name=_('Главный'))
    test = models.CharField(max_length=255, verbose_name=_('Дочерний'))

portal/phonebook/models.py
from django.db import models
from django.core.validators import RegexValidator


class Phone(models.Model):
    phone = models.CharField(max_length=8, verbose_name='Номер телефона')

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = 'Номер телефона'
        verbose_name_plural = 'Номера телефонов'
        ordering = ['phone']


class Department(models.Model):
    department = models.CharField(max_length=255, unique=True, verbose_name='Департамент')

    def __str__(self):
        return self.department

    class Meta:
        verbose_name = 'Департамент'
        verbose_name_plural = 'Департаменты'
        ordering = ['department']


class Division(models.Model):
    department = models.ForeignKey('Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='division')
    division = models.CharField(max_length=255, unique=True, verbose_name='Отдел')

    def __str__(self):
        return self.division

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'
        ordering = ['division']


class Employees(models.Model):
    fio = models.CharField(max_length=255, unique=True, verbose_name='Сотрудник')
    position = models.CharField(max_length=255, verbose_name='Должность')
    department = models.ForeignKey('Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='employees',)
    division = models.ForeignKey('Division', on_delete=models.PROTECT, verbose_name='Отдел', related_name='employees',
                                 null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    cellphone_regex = RegexValidator(regex=r'^\d{1}-\d{3}-\d{3}-\d{2}-\d{2}$',
                                     message="Номер телефона необходимо вводить в формате: «9-999-999-99-99».")
    cellphone = models.CharField(validators=[cellphone_regex], max_length=15, verbose_name='Сотовый телефон',
                                 blank=True, null=True)
    phone = models.ForeignKey('Phone', default='', on_delete=models.SET_DEFAULT, verbose_name='телефон',
                              null=True, blank=True)
    photo = models.ImageField(upload_to='employees_photos', verbose_name='Фото сотрудников', blank=True)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ['fio']


class Management(models.Model):
    CHOICES = [
        ('Руководство', 'Руководство'),
        ('Административный блок', 'Административный блок'),
        ('Администратор по информационной безопасности ', 'Администратор по информационной безопасности ')
    ]
    fio = models.CharField(max_length=255, unique=True, verbose_name='ФИО')
    position = models.CharField(max_length=255, verbose_name='Должность')
    choice = models.CharField(max_length=255, choices=CHOICES, verbose_name='Руководство')
    email = models.EmailField(blank=True, null=True)
    cellphone_regex = RegexValidator(regex=r'^\d{1}-\d{3}-\d{3}-\d{2}-\d{2}$',
                                     message="Номер телефона необходимо вводить в формате: «9-999-999-99-99».")
    cellphone = models.CharField(validators=[cellphone_regex], max_length=15, verbose_name='Сотовый телефон',
                                 blank=True, null=True)
    phone = models.ForeignKey('Phone', default='', on_delete=models.SET_DEFAULT, verbose_name='телефон',
                              null=True, blank=True)

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'Руководство'
        verbose_name_plural = 'Руководство'
        ordering = ['fio']

portal/phonebook/forms.py
from django import forms
from .models import *


class EmployeesForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['division'].queryset = Division.objects.none()

        if 'department' in self.data:
            try:
                department_id = int(self.data.get('department'))
                self.fields['division'].queryset = Division.objects.filter(department_id=department_id).order_by('division')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['division'].queryset = self.instance.department.division_set.order_by('division')


class EmployeesUpdateForm(forms.ModelForm):
    class Meta:
        model = Employees
        fields = '__all__'


class DepartmentForm(forms.ModelForm):
    class Meta:
        model = Department
        fields = '__all__'


class DivisionForm(forms.ModelForm):
    class Meta:
        model = Division
        fields = '__all__'

portal/phonebook/views.py
import http
from urllib import request
import io
import xlsxwriter
import xlwt
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, View
from .forms import *


class EmployeesListView(ListView):
    model = Employees
    context_object_name = 'employees'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        query = self.request.GET.get('q')
        if query:
            return qs.filter(Q(fio__icontains=query) |
                             Q(position__icontains=query) |
                             Q(department__department__icontains=query) |
                             Q(division__division__icontains=query) |
                             Q(phone__phone__icontains=query))
        return Employees.objects.filter()


class EmployeesCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Employees
    form_class = EmployeesForm
    success_message = "Сотрудник был успешно добавлен"
    success_url = reverse_lazy('phonebook')


def load_division(request):
    department_id = request.GET.get('department')
    divisions = Division.objects.filter(department_id=department_id).order_by('division')
    return render(request, 'phonebook/division_dropdown_list_options.html', {'divisions': divisions})


class EmployeesUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Employees
    initial = {'department': '', 'division': '', }
    form_class = EmployeesUpdateForm
    success_message = "Сотрудник был успешно изменен"
    success_url = reverse_lazy('phonebook')


class EmployeesDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Employees
    success_message = "Сотрудник был удален"
    success_url = reverse_lazy('phonebook')


class DepartmentListView(LoginRequiredMixin, ListView):
    model = Department
    context_object_name = 'departments'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        query = self.request.GET.get('q')
        if query:
            return qs.filter(Q(department__icontains=query))
        return Department.objects.filter()


class DepartmentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Department
    form_class = DepartmentForm
    success_message = "Департамент был успешно добавлен"
    success_url = reverse_lazy('departments')


class DepartmentUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Department
    form_class = DepartmentForm
    success_message = "Департамент был успешно изменен"
    success_url = reverse_lazy('departments')


class DepartmentDelete(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Department
    success_message = "Департамент был удален"
    success_url = reverse_lazy('departments')


class DivisionListView(LoginRequiredMixin, ListView):
    model = Division
    context_object_name = 'divisions'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        query = self.request.GET.get('q')
        if query:
            return qs.filter(Q(division__icontains=query) |
                             Q(department__department__icontains=query))
        return Division.objects.filter()


class DivisionCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Division
    form_class = DivisionForm
    success_message = "Отдел был успешно добавлен"
    success_url = reverse_lazy('divisions')


class DivisionUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Division
    form_class = DivisionForm
    success_message = "Отдел был успешно изменен"
    success_url = reverse_lazy('divisions')


class DivisionDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Division
    success_message = "Отдел был удален"
    success_url = reverse_lazy('divisions')


class DownloadPhonebook(View):
    def get(self, request):
        text = '«Қазмедиа орталығы» басқарушы компаниясы» ЖШС қызметкерлерінің телефон нөмірлері'
        output = io.BytesIO()
        workbook = xlsxwriter.Workbook(output)
        worksheet = workbook.add_worksheet('Телефонная книга')
        merge_format = workbook.add_format({
            'bold': True,
            'border': 6,
            'align': 'center',
            'valign': 'vcenter',
            'fg_color': '#D7E4BC',
        })
        worksheet.merge_range('A1:G7', text, merge_format)
        worksheet.set_column('A:Z', 35)
        data = Employees.objects.all().values_list('fio', 'position', 'department__department', 'division__division',
                                                   'email', 'cellphone', 'phone__phone')
        table_range = 'A10:G' + str(len(data) + 10)
        options = {'data': data,
                   'style': 'Table Style Light 11',
                   'columns': [{'header': 'ФИО'},
                               {'header': 'Должность'},
                               {'header': 'Департамент'},
                               {'header': 'Отдел'},
                               {'header': 'Email'},
                               {'header': 'Сотовый телефон'},
                               {'header': 'Рабочий телефон'},
                               ]}
        worksheet.add_table(table_range, options)
        workbook.close()
        output.seek(0)
        filename = 'Phonebook.xlsx'
        response = HttpResponse(
            output,
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
        )
        response['Content-Disposition'] = 'attachment; filename=%s' % filename

        return response

portal/phonebook/templates/phonebook/department_list.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans 'Департаменты' %}{% endblock %}

{% block content %}

<div class="container">
    <div class="p-5 mb-4 bg-light rounded-3 ">
        <h1 class="d-flex justify-content-center">{% trans 'Департаменты' %}</h1>
    </div>

    <form action="" method="get" class="">
        <div class="form-control input-group mb-5">
            <input type="text" class="form-control form-control-lg" placeholder="{% trans 'Поиск' %}" name="q">
            <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i> {% trans 'Поиск' %}</button>
        </div>
    </form>

    {% if messages %}
    {% for message in messages %}

    <div class="alert alert-{{ message.tags }}" id="message">
        <div class="modal-header">
            <h5 class="modal-title">{{ message }}</h5>
            <button type="button" id="close" class="btn-close" onClick=»closeIt()"></button>
        </div>
    </div>

    {% endfor %}
    {% endif %}

    {% if perms.phonebook.add_department %}
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-sm btn-primary" href="{% url 'department_add' %}">{% trans 'Добавить департамент' %}</a>
    </div>
    {% endif %}

    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead class="table-primary">
                <tr>
                    <th>#</th>
                    <th>Департамент</th>
                    <th>Департаменті</th>

                    {% if perms.phonebook.change_department or perms.phonebook.delete_department %}
                    <th style="width: 15%"></th>
                    {%endif%}

                </tr>
            </thead>

            <tbody>
            {% for department in departments %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ department.department_ru }}</td>
                    <td>{{ department.department_kk }}</td>

                    {% if perms.phonebook.change_department or perms.phonebook.delete_department %}
                    <td>
                        {% if perms.phonebook.change_department %}
                        <a class="btn btn-sm btn-warning" href="{% url 'department_update' department.id %}">{% trans 'Изменить' %}</a>
                        {% endif %}
                        {% if perms.phonebook.delete_department %}
                        <a class="btn btn-sm btn-danger" href="{% url 'department_delete' department.id %}">{% trans 'Удалить' %}</a>
                        {% endif %}
                    </td>
                    {% endif %}

                </tr>
            {% endfor %}
            </tbody>

        </table>

    </div>
</div>

<script>

     const message = document.getElementById("message");
     const btn = document.getElementById("close");
     btn.onclick = function () {
        message.style.display = "none";
        };

</script>

{% endblock %}

portal/phonebook/templates/phonebook/division_dropdown_list_options.html
<option value="">---------</option>
{% for division in divisions %}
<option value="{{ division.pk }}">{{ division.division }}</option>
{% endfor %}

portal/phonebook/templates/phonebook/employees_form.html
{% extends 'base.html' %}
{% load i18n static %}


{% block title %}
{% if form.fio.value %}
{% trans 'Изменение сотрудника' %}
{% else %}
{% trans 'Добавление сотрудника' %}
{% endif %}{% endblock %}

{% block content %}

<div class="container">

    <div class="p-5 mb-4 bg-light rounded-3 center">

        {% if form.fio.value %}
        <h1 class="d-flex justify-content-center">{% trans 'Форма изменения сотрудника' %}</h1>
        {% else %}
        <h1 class="d-flex justify-content-center">{% trans 'Форма добавления сотрудников' %}</h1>
        {% endif %}
        <p class="d-flex justify-content-center lead">{% trans 'Поля отмеченные звездочкой обязательны для заполнения' %}</p>

    </div>

    <div class="container-form">

        <form class="needs-validation" method="POST" id="employeesForm" enctype="multipart/form-data" data-division-url="{% url 'ajax_load_division' %}" novalidate>

            {% csrf_token %}

            <!-- fio -->
            <div class="row mb-4 d-none">
                <label class="col-sm-2 col-form-label">Сотрудник * :</label>
                <div class="col-sm-10">
                    <input type="text" name="fio" class="form-control" maxlength="255" placeholder="" id="id_fio" value="{{employees.fio}}" required autofocus>
                </div>
            </div>

            <!-- position -->
            <div class="row mb-4 d-none">
                <label class="col-sm-2 col-form-label">Должность * :</label>
                <div class="col-sm-10">
                    <input type="text" name="position" class="form-control" maxlength="255" placeholder="" id="id_position" value="{{employees.position}}" required autofocus>
                </div>
            </div>

            <!-- fio_ru -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">Сотрудник * :</label>
                <div class="col-sm-10">
                    <input type="text" name="fio_ru" class="form-control" maxlength="255" placeholder="" id="id_fio_ru" value="{{employees.fio_ru}}" required autofocus>
                </div>
            </div>

            <!-- fio_kk -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">Қызметкер * :</label>
                <div class="col-sm-10">
                    <input type="text" name="fio_kk" class="form-control" maxlength="255" placeholder="" id="id_fio_kk" value="{{employees.fio_kk}}" required autofocus>
                </div>
            </div>

            <!-- position_ru -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">Должность * :</label>
                <div class="col-sm-10">
                    <input type="text" name="position_ru" class="form-control" maxlength="255" placeholder="" id="id_position_ru" value="{{employees.position_ru}}" required autofocus>
                </div>
            </div>

            <!-- position_kk -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">Лауазымы * :</label>
                <div class="col-sm-10">
                    <input type="text" name="position_kk" class="form-control" maxlength="255" placeholder="" id="id_position_kk" value="{{employees.position_kk}}" required autofocus>
                </div>
            </div>


            <!-- department -->
            <div class="row mb-4">
                <label for="id_department" class="col-sm-2">{% trans 'Департамент' %} * :</label>
                <div class="col-sm-10">
                    <select id="id_department" class="form-select" name="department" required autofocus>
                        {% for id, name in form.fields.department.choices %}
                        <option value="{{ id }}" {% if form.instance.department.pk == id %} selected {% endif %}>{{ name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <!-- division -->
            <div class="row mb-4">
                <label for="id_division" class="col-sm-2">{% trans 'Отдел' %} * :</label>
                <div class="col-sm-10">
                    <select id="id_division" class="form-select" name="division">
                        {% for id, name in form.fields.division.choices %}
                        <option value="{{ id }}" {% if form.instance.division.pk == id %} selected {% endif %}>{{ name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <!-- email -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">{% trans 'Email' %} :</label>
                <div class="col-sm-10">
                    <input type="text" name="email" class="form-control" maxlength="255" placeholder="" id="id_email" value="{% if employees.email %} {{employees.email}} {% else %} &nbsp; {% endif %}" autofocus>
                </div>
            </div>

            <!-- cellphone -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">{% trans 'Сотовый телефон' %} :</label>
                <div class="col-sm-10">
                    <input type="text" name="cellphone" class="form-control" maxlength="255" placeholder="" id="id_cellphone" value="{% if employees.cellphone %} {{employees.cellphone}} {% else %} &nbsp; {% endif %}" autofocus>
                </div>
            </div>

            <!-- phone -->
            <div class="row mb-4">
                <label for="id_phone" class="col-sm-2">{% trans 'Телефон' %} * :</label>
                <div class="col-sm-10">
                    <select id="id_phone" class="form-select" name="phone">
                        {% for id, name in form.fields.phone.choices %}
                        <option value="{{ id }}" {% if form.instance.phone.pk == id %} selected {% endif %}>{{ name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <!-- Photo -->
            <div class="row mb-4">
                <div class="form-group image-group" id="id_image_group">
                    <img class="img-fluid image" src="{% if form.instance.photo %} {{employees.photo.url}} {% endif %}" id="id_image_display">
                    <div class="middle">
                        <div class="text">{% trans 'Изменить фото' %}</div>
                    </div>
                </div>
                <label class="col-sm-2 col-form-label">{% trans 'Фото' %} * :</label>
                <div class="col-sm-10">
                    <input type="file" name="photo" id="id_image_file" accept="image/*" onchange="readURL(this)"
                           value="{{employees.photo}}">
                </div>
            </div>

            <!-- Submit btn -->
            <div class="row">
                <div class="col-md-6">
                    <a class="btn btn-warning w-100 me-2" href="{% url 'phonebook' %}">{% trans 'Отменить' %}</a>
                </div>
                {% if form.fio.value %}
                <div class="col-md-6">
                    <button type="submit" class="btn btn-secondary w-100 btn_save">{% trans 'Изменить' %}</button>
                </div>
                {% else %}
                <div class="col-md-6">
                    <button type="submit" class="btn btn-secondary w-100 btn_save">{% trans 'Добавить' %}</button>
                </div>
                {% endif %}
            </div>

            {% if form.errors %}

            <div class="alert alert-danger alert-dismissible fade show mt-2">
                {% if form.errors.fio %}
                <strong>{% trans 'Сотрудник с таким ФИО уже существует' %}</strong>
                {% else %}
                <strong>{{ form.errors.email }}</strong>
                <strong>{{ form.errors.cellphone }}</strong>
                {% endif %}


                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>

            {% endif %}

        </form>

    </div>

<!-- список отделов -->

<script>

    departmentId = document.getElementById("id_department").value;
    if (departmentId) {
        var url = $("#employeesForm").attr("data-division-url");
        $.ajax({
            url: url,
            data: {
                'department': departmentId
                },
            success: function (data) {
                $("#id_division").html(data);
                }
            });
        }


    $("#id_department").change(function () {
        var url = $("#employeesForm").attr("data-division-url");
        var departmentId = $(this).val();

        $.ajax({
            url: url,
            data: {
                'department': departmentId
                },
            success: function (data) {
                $("#id_division").html(data);
                }
            });
        });


</script>

<!-- ошибки валидации -->

<script>
    // Self-executing function
    (function() {
        'use strict';
        window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
                form.addEventListener('submit', function(event) {
                    if (form.checkValidity() === false) {
                        event.preventDefault();
                        event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();

</script>


<!-- ввод в скрытые поля -->

<script>

    $('.btn_save').click(function(){ // отлавливаем нажатие
    var id_fio = $("#id_fio_ru").val(); // извлекаем текст из fio_ru
    var id_position_ru = $("#id_position_ru").val(); // извлекаем текст из id_position
    $("#id_fio").val(id_fio); //записываем текст в id_fio (меняем значение value)
    $("#id_position").val(id_position_ru); //записываем текст в id_position (меняем значение value)
    });

</script>

<!-- ввод изображения (красивый) -->

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
    	document.getElementById('id_image_file').click();
    };

	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
            $('#id_image_display')
                .attr('src', e.target.result)
        };
		reader.readAsDataURL(input.files[0]);
	}

</script>

</div>

{% endblock %}