portal/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from .views import *

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('birthday', views.BirthdayListView.as_view(), name='birthday'),
    path('add_birthday', views.BirthdayCreateView.as_view(), name='birthday_add'),
    path('update_birthday/<pk>/', views.BirthdayUpdateView.as_view(), name='update_birthday'),
    path('delete_birthday/<pk>/', views.BirthdayDelete.as_view(), name='delete_birthday'),
    path('send', send, name='send'),
    path('<slug:slug>', article_detail, name='article_detail'),
    path('maintest/', views.MaintestListView.as_view(), name='maintest'),
    path('maintest_add/', views.MaintestCreateView.as_view(), name='maintest_add'),
    path('maintest_update/<pk>/', views.MaintestUpdateView.as_view(), name='maintest_update'),
    path('maintest_delete/<pk>/', views.MaintestDeleteview.as_view(), name='maintest_delete'),
    path('parenttest/', views.ParenttestListView.as_view(), name='parenttest'),
    path('parenttest_add/', views.ParenttestCreateView.as_view(), name='parenttest_add'),
    path('parenttest_update/<pk>/', views.ParenttestUpdateView.as_view(), name='parenttest_update'),
    path('parenttest_delete/<pk>/', views.ParenttestDeleteview.as_view(), name='parenttest_delete'),
]

portal/portal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from portal import settings

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.urls')),
    path('phonebook/', include('phonebook.urls')),
    path('accounts/', include('accounts.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User, Group


class Birthday(models.Model):
    fio = models.CharField(max_length=255, unique=True, verbose_name='Сотрудник')
    fio_kk = models.CharField(max_length=255, unique=True, verbose_name='Қызметкер')
    position = models.CharField(max_length=255, verbose_name='Должность')
    position_kk = models.CharField(max_length=255, verbose_name='Қызмет атауы')
    date = models.DateField(verbose_name='День рождения')
    photo = models.ImageField(upload_to='birthday_photos', verbose_name='Фото')

    class Meta:
        verbose_name = 'День рождения'
        verbose_name_plural = 'Дни рождения'
        ordering = ['fio']

    def __str__(self):
        return self.fio


class News(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name=_('Новость'))
    slug = models.SlugField(unique=True)
    text = models.TextField(verbose_name=_('Текст'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Автор'))
    division = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name=_('Отдел'))

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'slug': self.slug})


class MainTest(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name=_('Родительский'))

    def __str__(self):
        return self.title


class ParentTest(models.Model):
    title = models.ForeignKey(MainTest, on_delete=models.CASCADE, verbose_name=_('Главный'))
    test = models.CharField(max_length=255, verbose_name=_('Дочерний'))

portal/phonebook/models.py
from django.db import models
from django.core.validators import RegexValidator


class Phone(models.Model):
    phone = models.CharField(max_length=8, verbose_name='Номер телефона')

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = 'Номер телефона'
        verbose_name_plural = 'Номера телефонов'
        ordering = ['phone']


class Department(models.Model):
    department = models.CharField(max_length=255, unique=True, verbose_name='Департамент')

    def __str__(self):
        return self.department

    class Meta:
        verbose_name = 'Департамент'
        verbose_name_plural = 'Департаменты'
        ordering = ['department']


class Division(models.Model):
    department = models.ForeignKey('Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='division')
    division = models.CharField(max_length=255, unique=True, verbose_name='Отдел')

    def __str__(self):
        return self.division

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'
        ordering = ['division']


class Employees(models.Model):
    fio = models.CharField(max_length=255, unique=True, verbose_name='Сотрудник')
    position = models.CharField(max_length=255, verbose_name='Должность')
    department = models.ForeignKey('Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='employees',)
    division = models.ForeignKey('Division', on_delete=models.PROTECT, verbose_name='Отдел', related_name='employees',
                                 null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    cellphone_regex = RegexValidator(regex=r'^\d{1}-\d{3}-\d{3}-\d{2}-\d{2}$',
                                     message="Номер телефона необходимо вводить в формате: «9-999-999-99-99».")
    cellphone = models.CharField(validators=[cellphone_regex], max_length=15, verbose_name='Сотовый телефон',
                                 blank=True, null=True)
    phone = models.ForeignKey('Phone', default='', on_delete=models.SET_DEFAULT, verbose_name='телефон',
                              null=True, blank=True)
    photo = models.ImageField(upload_to='employees_photos', verbose_name='Фото сотрудников', blank=True)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ['fio']


class Management(models.Model):
    CHOICES = [
        ('Руководство', 'Руководство'),
        ('Административный блок', 'Административный блок'),
        ('Администратор по информационной безопасности ', 'Администратор по информационной безопасности ')
    ]
    fio = models.CharField(max_length=255, unique=True, verbose_name='ФИО')
    position = models.CharField(max_length=255, verbose_name='Должность')
    choice = models.CharField(max_length=255, choices=CHOICES, verbose_name='Руководство')
    email = models.EmailField(blank=True, null=True)
    cellphone_regex = RegexValidator(regex=r'^\d{1}-\d{3}-\d{3}-\d{2}-\d{2}$',
                                     message="Номер телефона необходимо вводить в формате: «9-999-999-99-99».")
    cellphone = models.CharField(validators=[cellphone_regex], max_length=15, verbose_name='Сотовый телефон',
                                 blank=True, null=True)
    phone = models.ForeignKey('Phone', default='', on_delete=models.SET_DEFAULT, verbose_name='телефон',
                              null=True, blank=True)

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'Руководство'
        verbose_name_plural = 'Руководство'
        ordering = ['fio']

portal/main/forms.py
import os
from django import forms
from modeltranslation.forms import TranslationModelForm
from django.utils.translation import gettext as _

from django.forms import DateInput

from .models import *


class BirthdayForm(TranslationModelForm):
    class Meta:
        model = Birthday
        fields = ('fio', 'fio_kk', 'date', 'position', 'position_kk', 'photo')


class MaintestForm(forms.ModelForm):
    class Meta:
        model = MainTest
        fields = '__all__'


class ParenttestForm(forms.ModelForm):
    class Meta:
        model = ParentTest
        fields = ('test', 'test_ru', 'test_kk', 'title_ru', 'title_kk')

portal/main/views.py
import datetime

from django.conf.global_settings import STATIC_URL
from django.shortcuts import redirect, render, get_object_or_404
from modeltranslation.forms import TranslationModelForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.template.loader import render_to_string
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, TemplateView
from django.urls import reverse_lazy
from django.core.mail import EmailMessage
from html2image import Html2Image
from .forms import *
from django.db.models import Q
from django.contrib.messages.views import SuccessMessageMixin

from django.conf import settings
from django.core.mail import send_mail


class Index(TemplateView):

    template_name = 'main/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super(Index, self).get_context_data(*args, **kwargs)
        today = datetime.datetime.today()
        birthday = Birthday.objects.filter(date__month=today.month, date__day=today.day)
        context['birthday'] = birthday
        return context


class BirthdayListView(LoginRequiredMixin, ListView):
    model = Birthday
    context_object_name = 'birthday'

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        query = self.request.GET.get('q')
        if query:
            return qs.filter(Q(fio__icontains=query) |
                             Q(date__icontains=query))
        return Birthday.objects.filter()


class BirthdayCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Birthday
    form_class = BirthdayForm
    success_message = "День рождения был успешно добавлен"
    success_url = reverse_lazy('birthday')


class BirthdayUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Birthday
    form_class = BirthdayForm
    success_message = "День рождения был успешно изменен"
    success_url = reverse_lazy('birthday')


class BirthdayDelete(LoginRequiredMixin, SuccessMessageMixin,  DeleteView):
    model = Birthday
    success_message = "День рождения удален"
    success_url = reverse_lazy('birthday')


def send_card(request):
    today = datetime.datetime.today()
    birthday = Birthday.objects.filter(date__month=today.month, date__day=today.day)

    if birthday:
        print('Отправка письма')
        for b in birthday:

            # Путь к Открытке
            card = settings.STATICFILES_DIRS
            card = ''.join(card) + '/img/Открытка.png'

            # Данные ДР
            fio = b.fio
            position = b.position

            # Путь к фото ДР
            url = settings.MEDIA_ROOT
            new_url = url.rsplit("\\", 1)[0]
            photo = new_url + b.photo.url

            # Контекст для рендеринга
            context = {
                'fio': fio,
                'position': position,
                'photo': photo,
            }
            html = render_to_string('main/source_email.html', context)

            # Получение карточки
            folder = url + '/Card'
            print(folder)
            hti = Html2Image(output_path=folder)
            print(hti)
            fio_card = fio.rsplit(" ", 2)[0]
            filename = fio_card + '.jpg'
            hti.screenshot(html_str=html, save_as=filename, size=(724, 420))
            print('есть карточка')

            # Отправка письма
            image_path = folder + '/' + filename
            context = {'filename': image_path}
            html = render_to_string('main/email_card.html', context)
            subject = 'C Днем Рождения ' + fio
            print(subject)
            mail = EmailMessage(
                subject=subject,
                body=html,
                from_email='portal@kmo.kz',
                to=['zh.nurushev@kmo.kz'],
            )
            mail.content_subtype = "html"
            mail.send()
            print('письмо ушло')

    return redirect('birthday')


def send(request):
    today = datetime.datetime.today()
    birthday = Birthday.objects.filter(date__month=today.month, date__day=today.day)
    if birthday:
        for b in birthday:
            fio = b.fio
            position = b.position
            context = {
                'fio': fio,
                'position': position,
            }
        subject = 'Тема2'
        msg = 'Сообщение2'
        msg_html = render_to_string(f'D:/phone/WebSite3115555/index.html', context)
        send_mail(
            subject=subject,
            message=msg,
            html_message=msg_html,
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[settings.RECIPIENT_ADDRESS]
        )
        print('Письмо отправлено')
    else:
        print('Нет ДР')
    return redirect('birthday')


def article_detail(request, slug):
    instance = get_object_or_404(News, slug=slug)
    context = {
        'instance': instance
    }
    return render(request, 'main/article_detail.html', context)


class MaintestListView(ListView):
    model = MainTest
    context_object_name = 'maintest'


class MaintestCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = MainTest
    form_class = MaintestForm
    success_message = "Успешно добавлен"
    success_url = reverse_lazy('maintest')


class MaintestUpdateView(UpdateView):
    model = MainTest
    form_class = MaintestForm
    success_message = 'Успешно обнавлен'
    success_url = reverse_lazy('maintest')


class MaintestDeleteview(LoginRequiredMixin, SuccessMessageMixin,  DeleteView):
    model = MainTest
    success_message = "Удален"
    success_url = reverse_lazy('maintest')


class ParenttestListView(ListView):
    model = ParentTest
    context_object_name = 'parenttest'


class ParenttestCreateView(CreateView):
    model = ParentTest
    form_class = ParenttestForm
    success_message = "Успешно добавлен"
    success_url = reverse_lazy('parenttest')

    def form_valid(self, form):
        model = form.save(commit=False)
        print(form.cleaned_data)
        print(model.title.id)
        return super(ParenttestCreateView, self).form_valid(form)


class ParenttestUpdateView(UpdateView):
    model = ParentTest
    form_class = ParenttestForm
    success_message = 'Успешно обнавлен'
    success_url = reverse_lazy('parenttest')

    def form_valid(self, form):
        model = form.save(commit=False)
        print(form.cleaned_data)
        print('title - ' + model.title.id)
        print(model.title_ru.id)
        print(model.title_kk.id)
        return super(ParenttestCreateView, self).form_valid(form)


class ParenttestDeleteview(LoginRequiredMixin, SuccessMessageMixin,  DeleteView):
    model = ParentTest
    success_message = "Удален"
    success_url = reverse_lazy('parenttest')


class ParenttestUpdateView(UpdateView):
    model = ParentTest
    form_class = ParenttestForm
    success_message = 'Успешно обнавлен'
    success_url = reverse_lazy('parenttest')

portal/main/templates/main/birthday_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Удаление дня рождения{% endblock %}

{% block content %}

<div class="container">
    <div class="p-5 mb-4 bg-light rounded-3 center">
        <h1 class="d-flex justify-content-center">Дни рождения</h1>
        <p class="d-flex justify-content-center lead">Удаление дня рождения</p>
    </div>

    <div class="container mt-5">



            <div class="card text-center text-white bg-danger mb-4">
                <div class="card-body">

                    <h5 class="card-title">Вы уверены, что хотите удалить <span class="fw-bold fs-4"> "{{birthday.fio}}" </span> ?</h5>
                    <p class="card-text">Это не действие необратимо.</p>


                    <form action="{% url 'delete_birthday' birthday.id  %}" method="POST">

                        {% csrf_token %}
                        <a class="btn btn-warning w-25 me-2" href="{% url 'birthday' %}">Нет</a>
                        <button type="submit" class="btn btn-outline-dark w-25"><i class="bi-trash"></i>Удалить</button>

                    </form>
                </div>
            </div>




        </div>
    </div>

</div>

{% endblock %}>

portal/main/templates/main/birthday_list.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans 'Дни рождения' %}{% endblock %}

{% block content %}

<div class="container">

    <div class="p-5 mb-4 bg-light rounded-3 ">
        <h1 class="d-flex justify-content-center">{% trans 'Дни рождения' %}</h1>
    </div>

    <form action="" method="get" class="">
        <div class="form-control input-group mb-5">
            <input type="text" class="form-control form-control-lg" placeholder="{% trans 'Поиск' %}" name="q">
            <button type="submit" class="btn btn-primary"><i class="bi bi-search"></i>{% trans ' Поиск' %}</button>
        </div>
    </form>

    {% if perms.main.add_birthday %}
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-sm btn-primary me-2" href="{% url 'birthday_add' %}">{% trans 'Добавить день рождения' %}</a>
<!--        <a class="btn btn-sm btn-primary" href="{% url 'send' %}">Отправить письмо</a>-->

    </div>
    {% endif %}

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" id="message">
                <div class="modal-header" >
                    <h5 class="modal-title">{{ message }}</h5>
                    <button type="button" id="close" class="btn-close" onClick=»closeIt()"></button>
                </div>
            </div>

        {% endfor %}
    {% endif  %}


    <div class="row">

        {% for b in birthday %}

        <div class="col-sm-3 g-3 d-flex">
            <div class="card bg-light">
                <div class="row p-2 ">

                    <div class="col-sm-4 ">
                        <img src="{{ b.photo.url }}" class="card-img" alt="...">
                    </div>

                    <div class="col-sm-6">
                        <div class="card-button">
                            {% if perms.main.change_birthday %}
                            <a href="{% url 'update_birthday' b.id %}" class="btn btn-warning mb-2" data-bs-toggle="tooltip" data-bs-placement="top"
                               title="{% trans 'Изменить' %}"><i class="bi bi-pencil"></i></a>
                            {% endif %}
                            {% if perms.main.delete_birthday %}
                            <a href="{% url 'delete_birthday' b.id %}" class="btn btn-danger" data-bs-toggle="tooltip" data-bs-placement="top"
                               title="{% trans 'Удалить' %}"><i class="bi bi-x"></i></a>
                            {% endif %}
                        </div>

                        {% get_current_language as CURRENT_LANGUAGE %}
                        {% if CURRENT_LANGUAGE == 'ru' %}
                            <div class="card-body">
                                <h5 class="card-title">{{ b.fio }}</h5>
                            </div>
                        {% else %}
                            <div class="card-body">
                                <h5 class="card-title">{{ b.fio_kk }}</h5>
                            </div>
                        {% endif %}


                    </div>

                </div>

                <div class="card-body border-top">
                     {% get_current_language as CURRENT_LANGUAGE %}
                     {% if CURRENT_LANGUAGE == 'ru' %}
                        <p class="card-text">{{ b.position }}</p>
                     {% else %}
                        <p class="card-text">{{ b.position_kk }}</p>
                     {% endif %}
                    <p class="card-text">{% trans 'Дата рождения' %} - {{b.date}}</p>
                </div>

            </div>


        </div>

        {% endfor %}

    </div>

</div>

<script>
     const message = document.getElementById("message");
     const btn = document.getElementById("close");
     btn.onclick = function () {
        message.style.display = "none";
        };
</script>

{% endblock %}

portal/main/templates/main/maintest_confirm_delete.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans 'Удаление дня рождения' %}{% endblock %}

{% block content %}

<div class="container">
    <div class="p-5 mb-4 bg-light rounded-3 center">
        <h1 class="d-flex justify-content-center">{% trans 'Форма удаления' %}</h1>
    </div>

    <div class="container mt-5">



            <div class="card text-center text-white bg-danger mb-4">
                <div class="card-body">

                    <h5 class="card-title">{% trans 'Вы уверены, что хотите удалить' %} <span class="fw-bold fs-4"> "{{maintest.title}}" </span> ?</h5>
                    <p class="card-text">{% trans 'Это не действие необратимо' %}</p>


                    <form action="{% url 'maintest_delete' maintest.id  %}" method="POST">

                        {% csrf_token %}
                        <a class="btn btn-warning w-25 me-2" href="{% url 'maintest' %}">{% trans 'Нет' %}</a>
                        <button type="submit" class="btn btn-outline-dark w-25"><i class="bi-trash"></i>{% trans 'Удалить' %}</button>

                    </form>
                </div>
            </div>




        </div>
    </div>

</div>

{% endblock %}>

portal/main/templates/main/maintest_form.html
{% extends 'base.html' %}
{% load i18n static %}


{% block content %}

<div class="container">


    <div class="container-form mt-5">

        <form class="create-form" method="post" enctype="multipart/form-data">

            {% csrf_token %}

            <!-- title -->
            <div class="row mb-4 d-none">
                <label class="col-sm-2 col-form-label">Главный * :</label>
                <div class="col-sm-10">
                    <input type="text" name="title" class="form-control" maxlength="255" placeholder=""
                           id="id_title" value="{{maintest.title}}" required autofocus>
                </div>
            </div>

            <!-- title_ru -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">Главный_ru * :</label>
                <div class="col-sm-10">
                    <input type="text" name="title_ru" class="form-control" maxlength="255" placeholder=""
                           id="id_title_ru" value="{{maintest.title_ru}}" required autofocus>
                </div>
            </div>

            <!-- title_kk -->
            <div class="row mb-4">
                <label class="col-sm-2 col-form-label">Главный_kk * :</label>
                <div class="col-sm-10">
                    <input type="text" name="title_kk" class="form-control" maxlength="255" placeholder=""
                           id="id_title_kk" value="{{maintest.title_kk}}" required autofocus>
                </div>
            </div>

            <!-- Submit btn -->
            <div class="row">
                <div class="col-md-6">
                    <a class="btn btn-warning w-100 me-2" href="{% url 'maintest' %}">{% trans 'Отменить' %}</a>
                </div>
                {% if form.title.value %}
                <div class="col-md-6">
                    <button type="submit" class="btn btn-secondary w-100 btn_save">{% trans 'Изменить' %}</button>
                </div>
                {% else%}
                <div class="col-md-6">
                    <button type="submit" class="btn btn-secondary w-100 btn_save">{% trans 'Добавить' %}</button>
                </div>
                {% endif %}
            </div>


        </form>
    </div>



</div>

<script>
    $('.btn_save').click(function(){ // отлавливаем нажатие
     var id_title_ru = $("#id_title_ru").val(); // извлекаем текст из id_title_ru
    $("#id_title").val(id_title_ru); //записываем текст в id_title (меняем значение value)
});
</script>

{% endblock content %}

portal/main/templates/main/maintest_list.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans 'Главный тест' %}{% endblock %}

{% block content %}

<div class="container">


    <div class="p-5 mb-4 bg-light rounded-3">
        <h1 class="d-flex justify-content-center">{% trans 'Главный тест' %}</h1>
    </div>


    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" id="message">
        <div class="modal-header">
            <h5 class="modal-title">{{ message }}</h5>
            <button type="button" id="close" class="btn-close" onClick=»closeIt()"></button>
        </div>
    </div>

    {% endfor %}
    {% endif %}


    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-sm btn-primary" href="{% url 'maintest_add' %}"><i class="bi bi-person-plus me-1"></i>{% trans 'Добавить главный тест' %}</a>
    </div>


    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover text-center">
            <thead class="table-primary">
            <tr>
                <th>{% trans 'ru' %}</th>
                <th>{% trans 'kk' %}</th>
                {% if perms.phonebook.change_employees or perms.main.delete_maintest %}
                <th></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for m in maintest %}
            <tr>
                <td>{{ m.title_ru }}</td>
                <td>{{ m.title_kk }}</td>

                <td>
                    {% if perms.phonebook.change_employees %}
                    <a class="btn btn-sm btn-warning mb-2 w-100" href="{% url 'maintest_update' m.id %}">{% trans 'Изменить' %}</a>
                    {% endif %}
                    {% if perms.phonebook.delete_employees %}
                    <a class="btn btn-sm btn-danger w-100" href="{% url 'maintest_delete' m.id %}">{% trans 'Удалить' %}</a>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>

</div>

<script>
     const message = document.getElementById("message");
     const btn = document.getElementById("close");
     btn.onclick = function () {
        message.style.display = "none";
        };

</script>

{% endblock %}

portal/main/templates/main/parenttest_list.html
{% extends 'base.html' %}
{% load i18n static %}

{% block title %}{% trans 'Дочерний тест' %}{% endblock %}

{% block content %}

<div class="container">


    <div class="p-5 mb-4 bg-light rounded-3">
        <h1 class="d-flex justify-content-center">{% trans 'Дочерний тест' %}</h1>
    </div>


    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{ message.tags }}" id="message">
        <div class="modal-header">
            <h5 class="modal-title">{{ message }}</h5>
            <button type="button" id="close" class="btn-close" onClick=»closeIt()"></button>
        </div>
    </div>

    {% endfor %}
    {% endif %}


    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-sm btn-primary" href="{% url 'parenttest_add' %}"><i class="bi bi-person-plus me-1"></i>{% trans 'Добавить дочерний тест' %}</a>
    </div>


    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover text-center">
            <thead class="table-primary">
            <tr>
                <th>{% trans 'ru' %}</th>
                <th>{% trans 'kk' %}</th>
                {% if perms.phonebook.change_employees or perms.main.delete_maintest %}
                <th></th>
                {% endif %}
            </tr>
            </thead>
            <tbody>
            {% for p in parenttest %}
            <tr>
                <td>{{ p.test_ru }}</td>
                <td>{{ p.test_kk }}</td>

                <td>
                    {% if perms.phonebook.change_employees %}
                    <a class="btn btn-sm btn-warning mb-2 w-100" href="{% url 'parenttest_update' p.id %}">{% trans 'Изменить' %}</a>
                    {% endif %}
                    {% if perms.phonebook.delete_employees %}
                    <a class="btn btn-sm btn-danger w-100" href="{% url 'parenttest_delete' p.id %}">{% trans 'Удалить' %}</a>
                    {% endif %}
                </td>

            </tr>
            {% endfor %}
            </tbody>
        </table>


    </div>

</div>

<script>
     const message = document.getElementById("message");
     const btn = document.getElementById("close");
     btn.onclick = function () {
        message.style.display = "none";
        };

</script>

{% endblock %}