portal/main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

from .views import *

urlpatterns = [
    path('', views.Index.as_view(), name='home'),
    path('birthday', views.BirthdayListView.as_view(), name='birthday'),
    path('add_birthday', views.BirthdayCreateView.as_view(), name='birthday_add'),
    path('update_birthday/<pk>/', views.BirthdayUpdateView.as_view(), name='update_birthday'),
    path('delete_birthday/<pk>/', views.BirthdayDelete.as_view(), name='delete_birthday'),
    path('send', send, name='send'),
    path('<slug:slug>', article_detail, name='article_detail'),
    path('maintest/', views.MaintestListView.as_view(), name='maintest'),
    path('maintest_add/', views.MaintestCreateView.as_view(), name='maintest_add'),
    path('maintest_update/<pk>/', views.MaintestUpdateView.as_view(), name='maintest_update'),
    path('maintest_delete/<pk>/', views.MaintestDeleteview.as_view(), name='maintest_delete'),
    path('parenttest/', views.ParenttestListView.as_view(), name='parenttest'),
    path('parenttest_add/', views.ParenttestCreateView.as_view(), name='parenttest_add'),
    path('parenttest_update/<pk>/', views.ParenttestUpdateView.as_view(), name='parenttest_update'),
    path('parenttest_delete/<pk>/', views.ParenttestDeleteview.as_view(), name='parenttest_delete'),
]

portal/portal/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.views.i18n import JavaScriptCatalog

from portal import settings

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += i18n_patterns(
    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('main.urls')),
    path('phonebook/', include('phonebook.urls')),
    path('accounts/', include('accounts.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

portal/main/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User, Group


class Birthday(models.Model):
    fio = models.CharField(max_length=255, unique=True, verbose_name='Сотрудник')
    fio_kk = models.CharField(max_length=255, unique=True, verbose_name='Қызметкер')
    position = models.CharField(max_length=255, verbose_name='Должность')
    position_kk = models.CharField(max_length=255, verbose_name='Қызмет атауы')
    date = models.DateField(verbose_name='День рождения')
    photo = models.ImageField(upload_to='birthday_photos', verbose_name='Фото')

    class Meta:
        verbose_name = 'День рождения'
        verbose_name_plural = 'Дни рождения'
        ordering = ['fio']

    def __str__(self):
        return self.fio


class News(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name=_('Новость'))
    slug = models.SlugField(unique=True)
    text = models.TextField(verbose_name=_('Текст'))
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Автор'))
    division = models.ForeignKey(Group, on_delete=models.CASCADE, verbose_name=_('Отдел'))

    class Meta:
        verbose_name = 'Новость'
        verbose_name_plural = 'Новости'
        ordering = ['id']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_detail', kwargs={'slug': self.slug})


class MainTest(models.Model):
    title = models.CharField(max_length=255, unique=True, verbose_name=_('Родительский'))

    def __str__(self):
        return self.title


class ParentTest(models.Model):
    title = models.ForeignKey(MainTest, on_delete=models.CASCADE, verbose_name=_('Главный'))
    test = models.CharField(max_length=255, verbose_name=_('Дочерний'))

portal/phonebook/models.py
from django.db import models
from django.core.validators import RegexValidator


class Phone(models.Model):
    phone = models.CharField(max_length=8, verbose_name='Номер телефона')

    def __str__(self):
        return self.phone

    class Meta:
        verbose_name = 'Номер телефона'
        verbose_name_plural = 'Номера телефонов'
        ordering = ['phone']


class Department(models.Model):
    department = models.CharField(max_length=255, unique=True, verbose_name='Департамент')

    def __str__(self):
        return self.department

    class Meta:
        verbose_name = 'Департамент'
        verbose_name_plural = 'Департаменты'
        ordering = ['department']


class Division(models.Model):
    department = models.ForeignKey('Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='division')
    division = models.CharField(max_length=255, unique=True, verbose_name='Отдел')

    def __str__(self):
        return self.division

    class Meta:
        verbose_name = 'Отдел'
        verbose_name_plural = 'Отделы'
        ordering = ['division']


class Employees(models.Model):
    fio = models.CharField(max_length=255, unique=True, verbose_name='Сотрудник')
    position = models.CharField(max_length=255, verbose_name='Должность')
    department = models.ForeignKey('Department', on_delete=models.PROTECT, verbose_name='Департамент',
                                   related_name='employees',)
    division = models.ForeignKey('Division', on_delete=models.PROTECT, verbose_name='Отдел', related_name='employees',
                                 null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    cellphone_regex = RegexValidator(regex=r'^\d{1}-\d{3}-\d{3}-\d{2}-\d{2}$',
                                     message="Номер телефона необходимо вводить в формате: «9-999-999-99-99».")
    cellphone = models.CharField(validators=[cellphone_regex], max_length=15, verbose_name='Сотовый телефон',
                                 blank=True, null=True)
    phone = models.ForeignKey('Phone', default='', on_delete=models.SET_DEFAULT, verbose_name='телефон',
                              null=True, blank=True)
    photo = models.ImageField(upload_to='employees_photos', verbose_name='Фото сотрудников', blank=True)
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    update_date = models.DateTimeField(auto_now=True, verbose_name='Дата изменения')

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'Сотрудник'
        verbose_name_plural = 'Сотрудники'
        ordering = ['fio']


class Management(models.Model):
    CHOICES = [
        ('Руководство', 'Руководство'),
        ('Административный блок', 'Административный блок'),
        ('Администратор по информационной безопасности ', 'Администратор по информационной безопасности ')
    ]
    fio = models.CharField(max_length=255, unique=True, verbose_name='ФИО')
    position = models.CharField(max_length=255, verbose_name='Должность')
    choice = models.CharField(max_length=255, choices=CHOICES, verbose_name='Руководство')
    email = models.EmailField(blank=True, null=True)
    cellphone_regex = RegexValidator(regex=r'^\d{1}-\d{3}-\d{3}-\d{2}-\d{2}$',
                                     message="Номер телефона необходимо вводить в формате: «9-999-999-99-99».")
    cellphone = models.CharField(validators=[cellphone_regex], max_length=15, verbose_name='Сотовый телефон',
                                 blank=True, null=True)
    phone = models.ForeignKey('Phone', default='', on_delete=models.SET_DEFAULT, verbose_name='телефон',
                              null=True, blank=True)

    def __str__(self):
        return self.fio

    class Meta:
        verbose_name = 'Руководство'
        verbose_name_plural = 'Руководство'
        ordering = ['fio']

portal/templates/base.html
{% load i18n static %}
{% now "Y-m-d" as today_str %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% url 'javascript-catalog' %}"></script>
    <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
</head>

<body>

<header id="header">

    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light">

            <div class="d-flex justify-content-between align-items-center navbar-top">
                <ul class="navbar-left">
                    <li id="date"></li>
                    <li id="time"></li>
                </ul>
                <div>
                    <a class="navbar-brand" href="{% url 'home' %}"><img id="logo" src="{% static 'img/logo3.png' %}" alt=""/></a>
                </div>

                <div class="d-flex">
                    <ul class="navbar-right">
                        {% get_current_language as CURRENT_LANGUAGE %}
                        {% get_available_languages as AVAILABLE_LANGUAGES %}
                        {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
                        {% for language in languages %}
                            <li><a href="/{{ language.code }}/">{{ language.name_local }}</a></li>
                        {% endfor %}
                    </ul>
                    <ul class="social-media">
                        <li><a href="https://www.instagram.com/kazmedia_ortalygy/" target="blank"><i class="bi bi-instagram"></i></a></li>
                        <li><a href="https://www.facebook.com/qazmedia/" target="blank"><i class="bi bi-facebook"></i></a></li>
                        <li><a href="https://www.youtube.com/channel/UCMYPIaprCxS51FRg-v3keCg" target="blank"><i class="bi bi-youtube"></i> </a></li>
                    </ul>
                </div>

            </div>

            <div class="d-flex navbar-bottom-menu">
                <div class="navbar-collapse justify-content-center w-100">
                    <ul class="navbar-nav d-lg-flex justify-content-between align-items-center">
                        <li class="nav-item active"><a class="nav-link active" href="{% url 'home' %}"><i
                                class="bi bi-house-door me-1"></i>{% trans ' Главная' %}</a></li>
                        <li class="nav-item"><a class="nav-link active" href="{% url 'phonebook' %}"><i
                                class="bi bi-book me-1"></i>{% trans 'Телефонная книга' %}</a></li>

                        {% if perms.main.add_birthday or perms.main.change_birthday or perms.main.delete_birthday %}
                        <li class="nav-item"><a class="nav-link active" href="{% url 'birthday' %}"><i class="bi bi-window me-1"></i>{% trans 'Дни рождения' %}</a></li>
                        {% endif %}

                        {% if perms.phonebook.add_department or perms.phonebook.change_department or perms.phonebook.delete_department %}
                        <li class="nav-item"><a class="nav-link active" href="{% url 'departments' %}"><i class="bi bi-window me-1"></i>{% trans 'Департаменты' %}</a></li>
                        {% endif %}

                        {% if perms.phonebook.add_division or perms.phonebook.change_division or perms.phonebook.delete_division %}
                        <li class="nav-item"><a class="nav-link active" href="{% url 'divisions' %}"><i
                                class="bi bi-window-dock me-1"></i>{% trans 'Отделы' %}</a></li>
                        {% endif %}
                </div>

                <div class="navbar-collapse justify-content-end flex-shrink-0">
                    <ul class="navbar-nav d-lg-flex justify-content-end align-items-end">
                        {% if user.is_authenticated %}
                        <li class="nav-item"><a class="nav-link active" href="{% url 'logout' %}">{% trans 'Выход' %} | {{ user.get_username }}</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">{% trans 'Вход' %}</a></li>
                        {% endif %}
                    </ul>
                </div>

            </div>
        </nav>
    </div>
</header>


<script src="{% static 'js/date.js' %}"></script>





{% block content %}
{% endblock %}

</body>
</html>